# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Pipeline

on:
  push:
    branches:
      - master

jobs:
  job1:
    name: My name is Job1
    runs-on: ubuntu-latest
    steps:
      - name: First Step - Job 1
        run: echo "First Step in Job 1"
      - name: Create a File
        run: touch test.txt
  job2:
    name: My name is Job2
    runs-on: ubuntu-latest
    steps:
      - name: Verify the File - Job 2
        run: ls -l
